%YAML 1.2
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
name: global
components:
- name: adapter_video_buffer
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "VideoBuffer"
- name: adapter_bgr_u8
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "BGR_U8"
- name: adapter_rgb_u8
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "RGB_U8"
- name: adapter_bgr_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "BGR_F32"
- name: adapter_rgb_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "RGB_F32"
- name: adapter_planar_bgr_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "PLANAR_BGR_F32"
- name: adapter_planar_rgb_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "PLANAR_RGB_F32"
---
name: reshaper
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 0
    num_blocks: 40
- type: nvidia::gxf::MemoryAvailableSchedulingTerm
  parameters:
    allocator: allocator
    min_blocks: 1
- name: reshape_operator
  type: nvidia::isaac::tensor_ops::Reshape
  parameters:
    receiver: data_receiver
    transmitter: data_transmitter
    pool: allocator
    input_adapter: global/adapter_planar_rgb_f32
    output_adapter: global/adapter_planar_rgb_f32
    output_name: "input_tensor"
    output_shape: []
---
name: sink
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
---
components:
- type: nvidia::gxf::Connection
  parameters:
    source: reshaper/data_transmitter
    target: sink/signal
---
name: utils
components:
- name: clock
  type: nvidia::gxf::RealtimeClock
- type: nvidia::gxf::EventBasedScheduler
  parameters:
    clock: clock
    stop_on_deadlock: false
    worker_thread_number: 2
- type: nvidia::gxf::JobStatistics
  parameters:
    clock: clock
