%YAML 1.2
# Copyright (c) 2020-2022, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
---
name: inference
components:
- name: tx
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
    policy: 0
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: tx
    min_size: 1
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: rx
    min_size: 1
- name: rx
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
    policy: 0
- name: pool
  type: nvidia::gxf::UnboundedAllocator
- type: nvidia::gxf::TensorRtInference
  parameters:
    model_file_path: /tmp/model_file.onnx
    engine_file_path: /tmp/trt_engine.plan
    input_tensor_names:
        - input
    input_binding_names:
        - data
    output_tensor_names:
        - output
    output_binding_names:
        - mobilenetv20_output_flatten0_reshape0
    pool: pool
    cuda_stream_pool: utils/stream
    dummy_rx: rx
    rx: [rx]
    tx: tx
    force_engine_update: true
    verbose: true
    clock: utils/clock
---
name: vault
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: vault
  type: nvidia::gxf::Vault
  parameters:
    source: signal
    max_waiting_count: 1
    drop_waiting: false
---
name: connections
components:
- type: nvidia::gxf::Connection
  parameters:
    source: inference/tx
    target: vault/signal
---
name: utils
components:
- name: clock
  type: nvidia::gxf::RealtimeClock
- type: nvidia::gxf::GreedyScheduler
  parameters:
    clock: clock
    stop_on_deadlock: false
- name: stream
  type: nvidia::gxf::CudaStreamPool
  parameters:
    dev_id: 0
    stream_flags: 0
    stream_priority: 0
    reserved_size: 1
    max_size: 5
